package com.wex.gateways.silvio.purchase.model;

public enum CountryCurrency {
	AFGHANISTAN_AFGHANI("Afghanistan", "Afghani"),
	ALBANIA_LEK("Albania", "Lek"),
	ALGERIA_DINAR("Algeria", "Dinar"),
	ANGOLA_KWANZA("Angola", "Kwanza"),
	ANTIGUA_AND_BARBUDA_E_CARIBBEAN_DOLLAR("Antigua & Barbuda", "E. Caribbean Dollar"),
	ARGENTINA_PESO("Argentina", "Peso"),
	ARMENIA_DRAM("Armenia", "Dram"),
	AUSTRALIA_DOLLAR("Australia", "Dollar"),
	AZERBAIJAN_MANAT("Azerbaijan", "Manat"),
	BAHAMAS_DOLLAR("Bahamas", "Dollar"),
	BAHRAIN_DINAR("Bahrain", "Dinar"),
	BANGLADESH_TAKA("Bangladesh", "Taka"),
	BARBADOS_DOLLAR("Barbados", "Dollar"),
	BELARUS_NEW_RUBLE("Belarus", "New Ruble"),
	BELIZE_DOLLAR("Belize", "Dollar"),
	BENIN_CFA_FRANC("Benin", "CFA Franc"),
	BERMUDA_DOLLAR("Bermuda", "Dollar"),
	BOLIVIA_BOLIVIANO("Bolivia", "Boliviano"),
	BOSNIA_MARKA("Bosnia", "Marka"),
	BOTSWANA_PULA("Botswana", "Pula"),
	BRAZIL_REAL("Brazil", "Real"),
	BRUNEI_DOLLAR("Brunei", "Dollar"),
	BULGARIA_LEV_NEW("Bulgaria", "Lev New"),
	BURKINA_FASO_CFA_FRANC("Burkina Faso", "CFA Franc"),
	BURUNDI_FRANC("Burundi", "Franc"),
	CAMBODIA_RIEL("Cambodia", "Riel"),
	CAMEROON_CFA_FRANC("Cameroon", "CFA Franc"),
	CANADA_DOLLAR("Canada", "Dollar"),
	CAPE_VERDE_ESCUDO("Cape Verde", "Escudo"),
	CAYMAN_ISLANDS_DOLLAR("Cayman Islands", "Dollar"),
	CENTRAL_AFRICAN_REP_CFA_FRANC("Central African Rep.", "CFA Franc"),
	CHAD_CFA_FRANC("Chad", "CFA Franc"),
	CHILE_PESO("Chile", "Peso"),
	CHINA_RENMINBI("China", "Renminbi"),
	COLOMBIA_PESO("Colombia", "Peso"),
	COMOROS_FRANC("Comoros", "Franc"),
	CONGO_CFA_FRANC("Congo", "CFA Franc"),
	COSTA_RICA_COLON("Costa Rica", "Colon"),
	COTE_DIVOIRE_CFA_FRANC("Cote D'ivoire", "CFA Franc"),
	CUBA_CHAVITO("Cuba", "Chavito"),
	CUBA_PESO("Cuba", "Peso"),
	CZECH_REPUBLIC_KORUNA("Czech Republic", "Koruna"),
	DEM_REP_OF_CONGO_CONGOLESE_FRANC("Dem. Rep. of Congo", "Congolese Franc"),
	DENMARK_KRONE("Denmark", "Krone"),
	DJIBOUTI_FRANC("Djibouti", "Franc"),
	DOMINICAN_REPUBLIC_PESO("Dominican Republic", "Peso"),
	ECUADOR_DOLARES("Ecuador", "Dolares"),
	EGYPT_POUND("Egypt", "Pound"),
	EL_SALVADOR_DOLLAR("El Salvador", "Dollar"),
	EQUATORIAL_GUINEA_CFA_FRANC("Equatorial Guinea", "CFA Franc"),
	ERITREA_NAKFA("Eritrea", "Nakfa"),
	ESWATINI_LILANGENI("Eswatini", "Lilangeni"),
	ETHIOPIA_BIRR("Ethiopia", "Birr"),
	EURO_ZONE_EURO("Euro Zone", "Euro"),
	FIJI_DOLLAR("Fiji", "Dollar"),
	GABON_CFA_FRANC("Gabon", "CFA Franc"),
	GAMBIA_DALASI("Gambia", "Dalasi"),
	GEORGIA_LARI("Georgia", "Lari"),
	GHANA_CEDI("Ghana", "Cedi"),
	GRENADA_E_CARIBBEAN_DOLLAR("Grenada", "E.Caribbean Dollar"),
	GUATEMALA_QUENTZAL("Guatemala", "Quentzal"),
	GUINEA_BISSAU_CFA_FRANC("Guinea Bissau", "CFA Franc"),
	GUINEA_FRANC("Guinea", "Franc"),
	GUYANA_DOLLAR("Guyana", "Dollar"),
	HAITI_GOURDE("Haiti", "Gourde"),
	HONDURAS_LEMPIRA("Honduras", "Lempira"),
	HONG_KONG_DOLLAR("Hong Kong", "Dollar"),
	HUNGARY_FORINT("Hungary", "Forint"),
	ICELAND_KRONA("Iceland", "Krona"),
	INDIA_RUPEE("India", "Rupee"),
	INDONESIA_RUPIAH("Indonesia", "Rupiah"),
	IRAN_RIAL("Iran", "Rial"),
	IRAQ_DINAR("Iraq", "Dinar"),
	ISRAEL_SHEKEL("Israel", "Shekel"),
	JAMAICA_DOLLAR("Jamaica", "Dollar"),
	JAPAN_YEN("Japan", "Yen"),
	JORDAN_DINAR("Jordan", "Dinar"),
	KAZAKHSTAN_TENGE("Kazakhstan", "Tenge"),
	KENYA_SHILLING("Kenya", "Shilling"),
	KOREA_WON("Korea", "Won"),
	KUWAIT_DINAR("Kuwait", "Dinar"),
	KYRGYZSTAN_SOM("Kyrgyzstan", "Som"),
	LAOS_KIP("Laos", "Kip"),
	LEBANON_POUND("Lebanon", "Pound"),
	LESOTHO_MALOTI("Lesotho", "Maloti"),
	LIBERIA_DOLLAR("Liberia", "Dollar"),
	LIBYA_DINAR("Libya", "Dinar"),
	MADAGASCAR_ARIARY("Madagascar", "Ariary"),
	MALAWI_KWACHA("Malawi", "Kwacha"),
	MALAYSIA_RINGGIT("Malaysia", "Ringgit"),
	MALDIVES_RUFIYAA("Maldives", "Rufiyaa"),
	MALI_CFA_FRANC("Mali", "CFA Franc"),
	MARSHALL_ISLANDS_U_S_DOLLAR("Marshall Islands", "U.S. Dollar"),
	MAURITANIA_OUGUIYA("Mauritania", "Ouguiya"),
	MAURITIUS_RUPEE("Mauritius", "Rupee"),
	MEXICO_PESO("Mexico", "Peso"),
	MICRONESIA_US_DOLLAR("Micronesia", "U.S. Dollar"),
	MOLDOVA_LEU("Moldova", "LEU"),
	MONGOLIA_TUGRIK("Mongolia", "Tugrik"),
	MOROCCO_DIRHAM("Morocco", "Dirham"),
	MOZAMBIQUE_METICAL("Mozambique", "Metical"),
	MYANMAR_KYAT("Myanmar", "Kyat"),
	NAMBIA_DOLLAR("Nambia", "Dollar"),
	NEPAL_RUPEE("Nepal", "Rupee"),
	NETHERLANDS_ANTILLES_GUILDER("Netherlands Antilles", "Guilder"),
	NEW_ZEALAND_DOLLAR("New Zealand", "Dollar"),
	NICARAGUA_CORDOBA("Nicaragua", "Cordoba"),
	NIGER_CFA_FRANC("Niger", "CFA Franc"),
	NIGERIA_NAIRA("Nigeria", "Naira"),
	NORWAY_KRONE("Norway", "Krone"),
	OMAN_RIAL("Oman", "Rial"),
	PAKISTAN_RUPEE("Pakistan", "Rupee"),
	PALAU_DOLLAR("Palau", "Dollar"),
	PANAMA_DOLARES("Panama", "Dolares"),
	PAPUA_NEW_GUINEA_KINA("Papua New Guinea", "Kina"),
	PARAGUAY_GUARANI("Paraguay", "Guarani"),
	PERU_SOL("Peru", "Sol"),
	PHILIPPINES_PESO("Philippines", "Peso"),
	POLAND_ZLOTY("Poland", "Zloty"),
	QATAR_RIYAL("Qatar", "Riyal"),
	REP_OF_N_MACEDONIA_DENAR("Rep. of N. Macedonia", "Denar"),
	ROMANIA_NEW_LEU("Romania", "New Leu"),
	RUSSIA_RUBLE("Russia", "Ruble"),
	RWANDA_FRANC("Rwanda", "Franc"),
	SAO_TOME_AND_PRINCIPE_NEW_DOBRAS("Sao Tome & Principe", "New Dobras"),
	SAUDI_ARABIA_RIYAL("Saudi Arabia", "Riyal"),
	SENEGAL_CFA_FRANC("Senegal", "CFA Franc"),
	SERBIA_DINAR("Serbia", "Dinar"),
	SEYCHELLES_RUPEE("Seychelles", "Rupee"),
	SIERRA_LEONE_LEONE("Sierra Leone", "Leone"),
	SIERRA_LEONE_OLD_LEONE("Sierra Leone", "Old Leone"),
	SINGAPORE_DOLLAR("Singapore", "Dollar"),
	SOLOMON_ISLANDS_DOLLAR("Solomon Islands", "Dollar"),
	SOMALI_SHILLING("Somali", "Shilling"),
	SOUTH_AFRICA_RAND("South Africa", "Rand"),
	SOUTH_SUDAN_SUDANESE_POUND("South Sudan", "Sudanese Pound"),
	SRI_LANKA_RUPEE("Sri Lanka", "Rupee"),
	ST_LUCIA_E_CARIBBEAN_DOLLAR("St. Lucia", "E. Caribbean Dollar"),
	SUDAN_POUND("Sudan", "Pound"),
	SURINAME_DOLLAR("Suriname", "Dollar"),
	SWEDEN_KRONA("Sweden", "Krona"),
	SWITZERLAND_FRANC("Switzerland", "Franc"),
	SYRIA_POUND("Syria", "Pound"),
	TAIWAN_DOLLAR("Taiwan", "Dollar"),
	TAJIKISTAN_SOMONI("Tajikistan", "Somoni"),
	TANZANIA_SHILLING("Tanzania", "Shilling"),
	THAILAND_BAHT("Thailand", "Baht"),
	TIMOR_LESTE_DILI("Timor", "Leste-Dili"),
	TOGO_CFA_FRANC("Togo", "CFA Franc"),
	TONGA_PAANGA("Tonga", "Pa'anga"),
	TRINIDAD_AND_TOBAGO_DOLLAR("Trinidad & Tobago", "Dollar"),
	TUNISIA_DINAR("Tunisia", "Dinar"),
	TURKEY_NEW_LIRA("Turkey", "New Lira"),
	TURKMENISTAN_NEW_MANAT("Turkmenistan", "New Manat"),
	UGANDA_SHILLING("Uganda", "Shilling"),
	UKRAINE_HRYVNIA("Ukraine", "Hryvnia"),
	UNITED_ARAB_EMIRATES_DIRHAM("United Arab Emirates", "Dirham"),
	UNITED_KINGDOM_POUND("United Kingdom", "Pound"),
	URUGUAY_PESO("Uruguay", "Peso"),
	UZBEKISTAN_SOM("Uzbekistan", "Som"),
	VANUATU_VATU("Vanuatu", "Vatu"),
	VENEZUELA_BOLIVAR_SOBERANO("Venezuela", "Bolivar Soberano"),
	VENEZUELA_FUERTE_OLD("Venezuela", "Fuerte (OLD)"),
	VIETNAM_DONG("Vietnam", "Dong"),
	WESTERN_SAMOA_TALA("Western Samoa", "Tala"),
	YEMEN_RIAL("Yemen", "Rial"),
	ZAMBIA_NEW_KWACHA("Zambia", "New Kwacha"),
	ZIMBABWE_RTGS("Zimbabwe", "RTGS")
;

	private final String country;
	private final String currency;
	private final String countryCurrencyDescription;
	
	CountryCurrency(String country, String currency) {
		this.country = country;
		this.currency = currency;
		this.countryCurrencyDescription = country + "-" + currency;
	}
	

    public static CountryCurrency fromString(String description) {
        for (CountryCurrency cc : CountryCurrency.values()) {
            if (cc.countryCurrencyDescription.equalsIgnoreCase(description)) {
                return cc;
            }
        }
        return null;
    }

}
